version: "3.9"

networks:
  challenge-pic-pay-network:
    driver: bridge

services:
  challenge-pic-pay-db:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "picpay-desafio"
    ports:
      - "5432:5432"
    networks:
      - challenge-pic-pay-network
  challenge-pic-pay-api:
    build: .
    environment:
      DB_HOST: "challenge-pic-pay-db"
    ports:
      - "8080:8080"
    networks:
      - challenge-pic-pay-network
    depends_on:
      - challenge-pic-pay-db