name: Docker

on:
  workflow_call:
  
jobs:

  docker:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v4

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.3.0
     
    - name: Download Maven artifact
      uses: actions/download-artifact@v2
      with:
        name: maven-artifact  
        path: target/     
        
    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        username: gabrielv7
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.3.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: gabrielv7/challange-pic-pay-api:${{github.ref_name}}

