name: Docker

on:
  workflow_call:
  
jobs:
  docker:
    name: Deploy image to dockerHub
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v4

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.3.0
     
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.7
      with:
        name: app
        path: target/
        
    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        username: gabrielv7
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.3.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: gabrielv7/challange-pic-pay-api:latest
  deploy:
    needs: docker
    runs-on: [aws-ec2]
    steps:
      - name: Pull Image from docker hub
        run: sudo docker pull gabrielv7/challange-pic-pay-api:latest
      - name: Delete old container
        run: sudo docker rm -f challange-pic-pay-ap
      - name: Run Docker Image
        run: sudo docker run -d -p 8080:8080 --name spring-boot-app-container challange-pic-pay-api

