on:
  workflow_call:
  
jobs:
  EC2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: app
          path: target/
             
      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: /home/${{ secrets.REMOTE_USER }}/app/
          SOURCE: target/*.jar
          
      - name: Parando instancia anteiror da API
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            PID=$(sudo lsof -ti :8080)
            if [ ! -z "$PID" ]; then
                    sudo kill -9 $PID
                fi
          
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            if ! java -version &>/dev/null; then
              sudo yum install java-17-amazon-corretto-headless -y
            else
              echo "Java already installed"
            fi
            # Exportando variáveis de ambiente
            echo "export DB_HOST=${{ secrets.DB_HOST }}" >> ~/.bashrc
            echo "export DB_PORT=${{ secrets.DB_PORT }}" >> ~/.bashrc
            echo "export DB_NAME=${{ secrets.DB_NAME }}" >> ~/.bashrc
            echo "export DB_USER=${{ secrets.DB_USER }}" >> ~/.bashrc
            echo "export DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> ~/.bashrc
            source ~/.bashrc

            # Verificando variáveis de ambiente
            echo "DB_HOST=$DB_HOST"
            echo "DB_PORT=$DB_PORT"
            echo "DB_NAME=$DB_NAME"
            echo "DB_USER=$DB_USER"
            echo "DB_PASSWORD=$DB_PASSWORD"

            # Iniciando a aplicação
            nohup java -jar /home/${{ secrets.REMOTE_USER }}/app/*.jar > /home/${{ secrets.REMOTE_USER }}/output.log 2>&1 &
