on:
  workflow_call:
  
jobs:
  EC2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: app
          path: target/
             
      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: /home/${{ secrets.REMOTE_USER }}/app/
          SOURCE: target/*.jar

      - name: Update db url
        run: sed -i 's/<db_host>/${{ secrets.DB_HOST }}/' src/main/resources/application.properties
          
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo yum install java-17-amazon-corretto-headless -y
            export DB_HOST=${{ secrets.DB_HOST }}
            nohup java -jar /home/${{ secrets.REMOTE_USER }}/app/*.jar > output.log 2>&1 &
