on:
  workflow_call:
  
jobs:
  EC2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: app
          path: target/
          
      - name: Removendo jar antigo se existir
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            rm -rf /home/${{ secrets.REMOTE_USER }}/target 
                    
      - name: Copiando JAR para EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "./target/*.jar"
          target: "/home/${{ secrets.REMOTE_USER }}/target/"

      - name: Parando instancia anterior da API
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            PID=$(sudo lsof -ti :8080)
            if [ ! -z "$PID" ]; then
              sudo kill -9 $PID
            fi

      - name: Executando nova instancia da API
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo yum install java-17-amazon-corretto-headless -y
            export DB_HOST=${{ secrets.DB_HOST }}
            nohup java -jar /home/${{ secrets.REMOTE_USER }}/target/*.jar > /home/${{ secrets.REMOTE_USER }}/output.log 2>&1 &
