name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: build the docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        dockerfile: Dockerfile
        push: false
        tags: gabrielv7/challange-pic-pay-api:${{github.ref_name}}

    - name: login to docker hub
      uses: docker/login-action@v1
      with:
         username: gabrielv7
         password: ${{ secrets.PASSWORD_DOCKER_HUB }}

    - name: push the docker image to docker hub
      uses: docker/build-push-action@v4
      with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: gabrielv7/challange-pic-pay-api:${{github.ref_name}}
