name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'README.md'
      - '.github/workflows/**'
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

  build:
    runs-on: ubuntu-latest
    needs: setup-environment
    steps:
      - name: Build with Maven
        run: mvn compile

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run tests
        run: mvn test

  package:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Package application
        run: mvn package -DskipTests

      - name: Upload build artifact
        uses: actions/upload-artifact@v4.3.3
        with: 
          name: app
          path: target/*.jar

  docker:
    needs: package
    uses: ./.github/workflows/Docker.yml
    secrets: inherit

  # deploy-ec2:
  #   needs: docker
  #   uses: ./.github/workflows/EC2.yml
  #   secrets: inherit
